POST http://localhost:4000/v1/patients/createPatient
Content-Type: application/json

{
  "name": "Rahul E",
  "email": "rmtE@gmail.com",
  "address": "3 Park street",
  "dateOfBirth": "1990-01-01",
  "registeredDate": "2024-01-01"
}
