### GET request to example server
GET http://localhost:4004/api/patients
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0dXNlckB0ZXN0LmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3MzU3NDU2OCwiZXhwIjoxNzczNjEwNTY4fQ.fD4LdvdUynpspEd6qMjiqfXGPzv5Z21q4TtluYe4xVLe4VtR815K6RifYceUU6Hm
###