spring.application.name=patient-service

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
#spring.jpa.hibernate.ddl-auto=create
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

server.port=4000

logging.level.root=INFO